Pyet xarray
phydrus/pyet pull request #26
Opened 2022-10-13 06:27 UTC by mvremec

Update includes:
- compatibility with xarray.DataArray, so pyet can be used with netcdf data,
- improved testing (benchmarked to McMahon et al. 2013 and Schroedter 1985),
- improved documentation,
- added examples, ...

2022-10-14 06:36 UTC, raoulcollenteur requested changes

2022-10-14 06:36 UTC, raoulcollenteur commented on README.md
> +## Dimensions
Make it Pyet 1.2, and what about DataFrames?

2022-10-14 06:36 UTC, raoulcollenteur commented on pyet/version.py
> +__version__ = "1.1.1"
This should be 1.2.0b, cause you merge it into Dev ('b') and it is definitely more than a minor update.

2022-10-14 06:37 UTC, raoulcollenteur commented
We should really not merge into the Master, but first into Dev. And from there, merge Dev into Master.

2022-10-16 17:53 UTC, mvremec commented
Merge first to dew.

2022-10-16 17:53 UTC, closed without merging