removed extra argument given
phydrus/pyet pull request #78
Opened 2024-05-02 15:58 UTC by anshuverma2000

# Short Description
Add a short description describing the pull request (PR) here.

# Checklist before PR can be merged:
- [ ] closes issue #xxxx
- [ ] is documented
- [ ] Format code with [Black formatting](https://black.readthedocs.io)
- [ ] type hints for functions and methods
- [ ] tests added / passed
- [ ] Example Notebook (for new features)
- [ ] Remove output for all notebooks with changes

2024-05-02 16:54 UTC, VascoSch92 commented on pyet/radiation.py
> +        temp = (tmean + 5) / 68 / lambd
Can i suggest to put the parenthesis here to make clear which division is made first.

I'm sure the code is correct but it is not clear which is the first division :)

2024-05-06 11:57 UTC, mvremec commented
Thank you both for your contributions and for identifying the error! I just returned from holiday and will review the materials as soon as possible.

## I am proposing the following additions to the Checklist before this PR can be merged:
 - [ ] Add a Notebook outlining the different input options available for all methods. #77 
 - [ ] Update the documentation on ReadTheDocs per PM ASCE standards.  #70

2024-06-09 09:57 UTC, mvremec approved these changes
Thank you for noticing this!

2024-06-09 10:05 UTC, mvremec requested changes
I mistakenly approved this pull. After a more thorough review, here are some detailed thoughts on the changes:
1. Extra Argument: Thank you for catching that!
2. Datetime Check: There’s no need to add to_datetime since tmean should already be a DatetimeIndex. To ensure this, we should add a check for tmean.index.
3. Oudin Method: The implementation using "pet = pet.where((tmean + k2) >= 0, 0)" is correct as per our model requirements. Let’s keep this as is.

2024-06-09 10:05 UTC, mvremec commented on pyet/radiation.py
I mistakenly approved this pull. After a more thorough review, here are some detailed thoughts on the changes:
1. Extra Argument: Thank you for catching that!
2. Datetime Check: There’s no need to add to_datetime since tmean should already be a DatetimeIndex. To ensure this, we should add a check for tmean.index.
3. Oudin Method: The implementation using "pet = pet.where((tmean + k2) >= 0, 0)" is correct as per our model requirements. Let’s keep this as is.

2024-06-09 10:42 UTC, mvremec commented on pyet/radiation.py
> +        temp.index = to_datetime(temp.index)
Why use "to_datetime"? The temp should already be DatetimeIndex?

Thank you for your contributions!

2024-06-09 11:19 UTC, mvremec commented
Hi @anshuverma2000,

Thank you for catching the extra argument! I'd appreciate your insights on a couple of other points to help us address the issues effectively:
- Input Data Type: Could you confirm whether you are using xarray.DataArray or pandas.Series as input? This will help us understand the context better.
- Error Details: Can you provide more specifics about when and under what circumstances the error with NaNs occurred?
Thank you for your collaboration!

Best,
Matevz

2026-05-13 05:52 UTC, raoulcollenteur commented
Closing issue because no reply was given.

2026-05-13 05:52 UTC, closed without merging